### ISSUE TITLE
Android Nougat: test/simple/test-child-process-stdio-inherit.js fails

### ISSUE THREAD

**Issue by enricogior** [thaliproject/jxcore#53]
```
AssertionError: "" == "asdfasdf" ( 0:0)
    at equal (assert.js:136:11)
    at grandparent/< (/data/local/tmp/jxcore/test/simple/test-child-process-stdio-inherit.js:30:5)
    at emit (events.js
```

child.stdout.on('data'...) doesn't get called because the child process dies before the event is emitted or captured.

**Comment by enricogior** [comment]
test/simple/test-cluster-master-error.js seems to have a similar problem: the forked process exits with return value 0 instead of auto-killing itself (expected return code != 0).
