### ISSUE TITLE
Is 'jx install' different than 'jx npm install'?

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/jxcore#61]
Marek noticed that if he uses 'jx install' he doesn't have to set various environment variables with our paths and such but with 'jx npm install' he does. Did we set the paths for one but not the other?

**Comment by czyzm** [comment]
Issue may be observed with leveldown-mobile installation.
jx npm install leveldown-mobile fails with:

> gyp JXcore NODE-GYP Using node-gyp bundled in npm coming from JXcore
> gyp ERR! UNCAUGHT EXCEPTION 
> gyp ERR! stack TypeError: Arguments to path.resolve must be strings
> gyp ERR! stack     at Object.exports.resolve (path.js:296:15)
> gyp ERR! stack     at install (/Users/mczyz/.jx/npm/node_modules/node-gyp/lib/install.js:73:21)
> gyp ERR! stack     at Object.self.commands.(anonymous function) [as install] (/Users/mczyz/.jx/npm/node_modules/node-gyp/lib/node-gyp.js:66:37)
> gyp ERR! stack     at getNodeDir (/Users/mczyz/.jx/npm/node_modules/node-gyp/lib/configure.js:155:20)
> gyp ERR! stack     at /Users/mczyz/.jx/npm/node_modules/node-gyp/lib/configure.js:108:9
> gyp ERR! stack     at ChildProcess.exithandler (child_process.js:663:7)
> gyp ERR! stack     at ChildProcess.emit (events.js:85:17)
> gyp ERR! stack     at maybeClose (child_process.js:773:16)
> gyp ERR! stack     at Socket.<anonymous> (child_process.js:994:11)
> gyp ERR! stack     at Socket.emit (events.js:82:17)
> gyp ERR! System Darwin 15.6.0
> gyp ERR! command "/usr/local/bin/jx" "/Users/mczyz/.jx/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
> gyp ERR! cwd /Users/mczyz/thali/test/dummy/node_modules/leveldown-mobile
> gyp ERR! node -v v0.10.40
> gyp ERR! node-gyp -v v3.0.3
> gyp ERR! This is a bug in `node-gyp`.
> gyp ERR! Try to update node-gyp and file an Issue if it does not help:
> gyp ERR!     <https://github.com/nodejs/node-gyp/issues>
> npm WARN ENOENT ENOENT, open '/Users/mczyz/thali/test/dummy/package.json'
> npm WARN EPACKAGEJSON dummy No description
> npm WARN EPACKAGEJSON dummy No repository field.
> npm WARN EPACKAGEJSON dummy No README data
> npm WARN EPACKAGEJSON dummy No license field.
> npm ERR! Darwin 15.6.0
> npm ERR! argv "/usr/local/bin/jx" "/Users/mczyz/.jx/npm/bin/npm-cli.js" "--loglevel" "http" "--color" "true" "install" "leveldown-mobile"
> npm ERR! node v0.10.40
> npm ERR! npm  v3.3.12
> npm ERR! code ELIFECYCLE

jx install leveldown-mobile is successful.

Setting JX_NPM_JXB=jxb311 in environment makes the jx npm version successful as well.

**Comment by yaronyg** [comment]
Investigating now

**Comment by chapko** [comment]
It may be useful:

```
» jx install left-pad -dd
npm info it worked if it ends with ok
npm verb cli [ '/home/eugene/workspace/thali/jxcore-build/bin/jx-v8',
npm verb cli   '/home/eugene/.jx/npm/bin/npm-cli.js',
npm verb cli   'install',
npm verb cli   '--loglevel',
npm verb cli   'http',
npm verb cli   '--color',
npm verb cli   'true',
npm verb cli   'left-pad',
npm verb cli   '-dd',
npm verb cli   '--build-from-source' ]
npm info using npm@3.3.12
npm info using node@v0.10.40
npm info using jxcore@v0.3.1.4
...

» jx npm install left-pad -dd
npm info it worked if it ends with ok
npm verb cli [ '/home/eugene/workspace/thali/jxcore-build/bin/jx-v8',
npm verb cli   '/home/eugene/.jx/npm/bin/npm-cli.js',
npm verb cli   '--loglevel',
npm verb cli   'http',
npm verb cli   '--color',
npm verb cli   'true',
npm verb cli   'install',
npm verb cli   'left-pad',
npm verb cli   '-dd' ]
npm info using npm@3.3.12
npm info using node@v0.10.40
npm info using jxcore@v0.3.1.4
...
```

`jx install` and `jx npm install` use different parameters for npm-cli (`jx npm install` does not add `--build-from-source` parameter)

**Comment by enricogior** [comment]
Found the problem in `deps/npm/lib/_jx.js`, the `setVariables` function fails to locate the `install` comand when called from `jx npm install`, now we need to understand if the fix is the right one.

**Comment by yaronyg** [comment]
Diego has found the problem and has proposed a solution and Enrico needs to look at it.
