### ISSUE TITLE
Build fails on Travis because of test-tls-psk-client.js 

### ISSUE THREAD

**Issue by enricogior** [thaliproject/jxcore#64]
Travis uses Ubuntu 12.04, we tested on macOS and Linux 16.04, so this is something we didn't encounter and we will have to investigate. It may be caused by an old version of OpenSSL on the Travis machine. The test failed should be able to detect it and skip.
```
=== release test-tls-psk-client.js ===
Path: simple/test-tls-psk-client.js
exists
Using default temp DH parameters
Using default temp ECDH parameters
ACCEPT
client connected
secure error: Error: socket hang up
ERROR
47323619255072:error:140F2044:SSL routines:SSL3_SEND_SERVER_HELLO:internal error:s3_srvr.c:1495:
client close
killed
WAIT-ACCEPT
AssertionError: 0 == -1 ( 0:0)
    at equal (assert.js:136:27)
    at /home/travis/build/thaliproject/jxcore/test/simple/test-tls-psk-client.js:212:5
    at emit (events.js
Command: out/Release/jx /home/travis/build/thaliproject/jxcore/test/simple/test-tls-psk-client.js
[02:58|% 100|+ 624|-   1|-  16]: Done
make: *** [test-simple] Error 1
```

**Comment by yaronyg** [comment]
We know this works on the version of OpenSSL that we are using. The fix for this is to upgrade the Travis VM (even dynamically with a script) to the same version. For now we'll move this to Icebox.
