### ISSUE TITLE
Getting error loading jxb311.tar.gz

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/jxcore#84]
This particular error shows up when I run https://github.com/thaliproject/Thali_CordovaPlugin/blob/aaf35e740ed7aeb7661258028b64a4bdfb27d4b7/thali/install/setUpDesktop.sh#L50 I get the error:

```
> leveldown-mobile@1.1.1 install /Users/yarongoland/Desktop/depots/Thali_CordovaPlugin/test/www/jxcore/node_modules/leveldown-mobile
> "/usr/local/bin/jx" /Users/yarongoland/.jx/npm/node_modules/node-gyp/bin/node-gyp.js rebuild

gyp JXcore NODE-GYP Using node-gyp bundled in npm coming from JXcore
gyp http GET https://nodejs.org/jxb311.tar.gz
gyp http 404 https://nodejs.org/jxb311.tar.gz
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: 404 response downloading https://nodejs.org/jxb311.tar.gz
gyp ERR! stack     at Request.<anonymous> (/Users/yarongoland/.jx/npm/node_modules/node-gyp/lib/install.js:231:14)
gyp ERR! stack     at Request.emit (events.js:98:20)
gyp ERR! stack     at Request.onRequestResponse (/Users/yarongoland/.jx/npm/node_modules/request/request.js:998:10)
gyp ERR! stack     at ClientRequest.emit (events.js:82:17)
gyp ERR! stack     at HTTPParser.parserOnIncomingClient (http.js:1317:21)
gyp ERR! stack     at HTTPParser.parserOnHeadersComplete [as onHeadersComplete] (_jx_parsers.js:62:23)
gyp ERR! stack     at CleartextStream.socketOnData (http.js:1209:20)
gyp ERR! stack     at CleartextStream.read [as _read] (tls.js:477:12)
gyp ERR! stack     at CleartextStream.Readable.read (_stream_readable.js:308:10)
gyp ERR! stack     at EncryptedStream.write [as _write] (tls.js:336:25)
gyp ERR! System Darwin 16.1.0
gyp ERR! command "/usr/local/bin/jx" "/Users/yarongoland/.jx/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/yarongoland/Desktop/depots/Thali_CordovaPlugin/test/www/jxcore/node_modules/leveldown-mobile
gyp ERR! node -v v0.10.40
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
```

**Comment by yaronyg** [comment]
So it turns out that we made a change to setUpDesktop.sh that now sets NVM_NODEJS_ORG_MIRROR and JX_NPM_JXB such that if those values are already defined in the environment then we accept them otherwise we set them to our values. 

But this is a problem if you are using NVM which actually sets NVM_NODEJS_ORG_MIRROR to (rightfully) point at itself which isn't the value we need.

So the right solution is to get JXcore to stop looking to NVM_NODEJS_ORG_MIRROR in process-release.js and instead replace it with JXCORE_NODEJS_ORG_MIRROR so we don't have the conflict.
